### ISSUE TITLE
Should the gitlab API token be settable in gitlab_runner_runners?

### ISSUE THREAD

**Issue by btravouillon** [lgatellier/ansible-gitlab-runner-compose#4]
In the code below, the GitLab URL can change but not the GitLab API token.

https://github.com/lgatellier/ansible-gitlab-runner-compose/blob/a709b50c8fbb8819b734c0fa59b3338cbca30752/tasks/single-runner.yml#L22-L23

Would it be possible to define the API token in `gitlab_runner_runners` as well?

Example:
```
# Define default GitLab API token
gitlab_runner_api_token: mysecureapitoken

# Define runners list as below
gitlab_runner_runners:
  - gitlab_url: https://my.gitlab.url
    group: my/group
    registration_token: mysecuregrouptoken
  - gitlab_url: https://other.gitlab.url
    group: foo/bar
    api_token: myotherapitoken
    registration_token: mysecuregrouptoken
```

Something similar to this maybe?
```
api_token: "{{ item.api_token | default(gitlab_runner_api_token) }}" 
```
